version: 2.1
parameters:
  image-tag:
    type: string
    default: "current"
  orb-version:
    type: string
    default: "2.0"

orbs:
  aws-cli: circleci/aws-cli@<< pipeline.parameters.orb-version >>

jobs:
  build:
    docker:
      - image: cimg/node:<< pipeline.parameters.image-tag >>
    environment:
      IMAGETAG: << pipeline.parameters.image-tag >>
    steps:
      - run: echo "Image tag used was ${IMAGETAG}"
      
workflows:
  main:
    jobs:
     - build:
         context: org-global

