version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

# our defined job, and its steps
jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run: sed -i 's/$ORB_VERSION/$CIRCLE_ORB_VERSION/g' .circleci/continue-config.yml
      - continuation/continue:
          configuration_path: .circleci/continue-config.yml

workflows:
  setup:
    jobs:
      - setup:
          context: org-global
