version: 2.1
orbs:
  aws-cli: circleci/aws-cli@$ORB_VERSION
  
jobs:
  job-1:
    executor: aws-cli/default
    steps:
    - checkout
    - aws-cli/setup
    
workflows:
  main:
    jobs:
    - job-1
